// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSharp_Test.Models
{
    public partial class apply_file
    {
        [Key]
        public Guid id { get; set; }
        public Guid user_id { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string file_path { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? created_at { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? updated_at { get; set; }

        [ForeignKey("user_id")]
        [InverseProperty("apply_file")]
        public virtual users user { get; set; }
    }
}