// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace CSharp_Test.Models
{
    public partial class C_TestContext : DbContext
    {
        public C_TestContext()
        {
        }

        public C_TestContext(DbContextOptions<C_TestContext> options)
            : base(options)
        {
        }

        public virtual DbSet<apply_file> apply_file { get; set; }
        public virtual DbSet<orgs> orgs { get; set; }
        public virtual DbSet<syslog> syslog { get; set; }
        public virtual DbSet<users> users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<apply_file>(entity =>
            {
                entity.Property(e => e.id).ValueGeneratedNever();

                entity.HasOne(d => d.user)
                    .WithMany(p => p.apply_file)
                    .HasForeignKey(d => d.user_id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__apply_fil__user___37A5467C");
            });

            modelBuilder.Entity<orgs>(entity =>
            {
                entity.Property(e => e.id).ValueGeneratedNever();
            });

            modelBuilder.Entity<users>(entity =>
            {
                entity.Property(e => e.id).ValueGeneratedNever();

                entity.HasOne(d => d.org)
                    .WithMany(p => p.users)
                    .HasForeignKey(d => d.org_id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__users__org_id__34C8D9D1");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}